### PR TITLE
[WIP] Completing OAuth

### LINKED ISSUE #24: Let's complete UserOAuth[part1]
After we get user's GitHub username from [this](https://github.com/kossiitkgp/kwoc20-backend/blob/master/controllers/UserOAuth.go#L72) variable 
Using the username, check if the user already exists or not,
**if a new user**: 
Add the username in the database from the ["login" key](https://github.com/kossiitkgp/kwoc20-backend/blob/master/controllers/UserOAuth.go#L74) 
Send a JSON to the frontend in this format
{ "username" : "string", "name": "string", "email" : "string", "type" :"mentor or student based on state as shown [here](https://github.com/kossiitkgp/kwoc20-backend/blob/master/controllers/UserOAuth.go#L32)", 
"reg_type" : "new" }

You can obtain the key names from lines after [this](https://github.com/kossiitkgp/kwoc20-backend/blob/master/controllers/UserOAuth.go#L74)

Explanation of some pairs
- the "type" will telll whether its a mentor or not
- the "reg_type" will tell whether user should be redirected to dashboard or a form where name and email needs to be filed. Since reg_type is new, the user wll be redirected to form.

If the user already exists,
it involves JWT hence lets make it in another issue,

PS - before u startworking on the UserOAuth.go,, please change the variable names appropirately like at many places it is written mentor1, mentorOAuth, at such places make it userOAuth please

### PR DESCRIPTION
**Pull request by grapheo12**
This PR is due to the sprint initiated by the pep talk given by Raghavendra Maheshwari.

- Cleared Oauth issue (Closes #24 )
- Created a middleware that, given the input and output formats as structs, facilitates JSON input and output.
This will remove the boilerplate of JSON Marshalling and Unmarshalling.
- Moved DB operations to `utils/database.go` so that all db credentials have single point of usage.
- Moved all subroutes to `routes/`.
- Added `.env`.

More coming soon.

### CODE REVIEW

**Comment by grapheo12** [comment]
@rakaar The OAuth flow doesn't seem to follow: https://docs.github.com/en/developers/apps/authorizing-oauth-apps
Why?

**Comment by rakaar** [comment]
wait @grapheo12 
milke decide karte hai

**Comment by rakaar** [comment]
>@rakaar The OAuth flow doesn't seem to follow: https://docs.github.com/en/developers/apps/authorizing-oauth-apps
Why?

what exactly is not according to the docs?
 i also tested it using postman and i was successful in getting user data from github the final step in authentication

**Comment by grapheo12** [comment]
Sorry! I misread the doc.
Actually everything is just fine.

Just one thing though, `state` should be a random string. You are using state to pass user type.

**Comment by rakaar** [comment]
>Just one thing though, state should be a random string. You are using state to pass user type.

i have secret plan with it
cant discuss here

i wil tell u why i dint put it a random string
that was on purpose

**Comment by grapheo12** [comment]
Lol, secret plans with Open Source code!!

**Comment by grapheo12** [comment]
By the way, I created a testing html page, where you can test the oauth end to end. Pushing that in a moment.

**Comment by rakaar** [comment]
i tested it on postman 
it worked perfectly well


the oauth part on frontend is also ready
i tried to integrate but the cors error persists, if possible fix that also naa

**Comment by rakaar** [comment]
>Created a middleware that, given the input and output formats as structs, facilitates JSON input and output.
This will remove the boilerplate of JSON Marshalling and Unmarshalling

this is really cool !

**Comment by rakaar** [comment]
@grapheo12 
please don't write complete parts related to JWT token
in kwoc_backend also i proposed a messaged tagging u regarding scraping JWT and using a simpler methods for different reasons

lets once properly decide that proceed naa please
baaki, you can complete other things - Project details linking with mentor id stuff

P.S Raghavendra Maheshwari kya hai bhai

**Comment by grapheo12** [comment]
@rakaar Are you trying to fetch data from a popup window?

**Comment by grapheo12** [comment]
Run the server and check `http://lvh.me:8000/test/oauth` for a full OAuth flow.
The CORS issue you are facing is maybe due to the fact that frontend and backend are in different domains / same domain different ports. We really need server side rendering here.
When we host the app in production, we need to make sure that, `kwoc.kossiitkgp.org` points to the frontend and `kwoc.kossiitkgp.org/api` points to our backend. Even `api.kwoc.kossiitkgp.org` won't work.
How to achieve that requires a fair bit of discussion.

**Comment by grapheo12** [comment]
@rakaar Can you restructure the existing JSON apis to use `utils/jsonio.go`?
It now has an added error handling support (can recover from unhandled panics)

**Comment by rakaar** [comment]
>The CORS issue you are facing is maybe due to the fact that frontend and backend are in different domains / same domain different ports. We really need server side rendering here.

why is so easy in express, flask and django.
is there any package that simply can be used as middle ware to avoid cors. like basically to tell backend to send responses to any place, no matter from wheere request is coming.

**Comment by rakaar** [comment]
>Are you trying to fetch data from a popup window?

no, ye kaha se aaya ?
after github redirects to the `redirect_uri` register, in extension to the url, it adds some parameters  - code and state , which are being sent to backend

**Pull request merged**
