### PR TITLE
Fixes #20

### LINKED ISSUE #20: Add a makefile
Every GO Project has a `makefile` which can be used to automate some repetitive tasks, such as -
* building the codebase
* Linting and formatting
* Running tests
* Having a local deployment(in case of frontend code)
We can add one for our project :)

### PR DESCRIPTION
**Pull request by Holmes7**
Fixes #20 
Build and Lint targets added to Makefile.
Added .DS_Store to .gitignore

### CODE REVIEW

**Comment by Holmes7** [comment]
@rakaar @yashrsharma44 
I have made the changes. Please review the PR.

**Comment by rakaar** [comment]
Also it will be nice if you also update `docs.md` regarding the makefile @Holmes7

**Comment by yashrsharma44** [comment]
https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by yashrsharma44** [comment]
@rakaar did you run the makefile, because it wasn't working in my case

**Comment by rakaar** [comment]
On running the makefile, the output
image

**Comment by rakaar** [comment]
And it works well too
image

**Comment by Holmes7** [comment]
@rakaar I have added documentation for Makefile

**Comment by yashrsharma44** [comment]
I'll take a look tomorrow

**Comment by yashrsharma44** [comment]
@Holmes7 Can you add the following lines - 
```
help:
	@echo "Makefile for automating tasks"
	@echo "build : run make build for building the codebase"
	@echo "lint : run make lint for running lint checks"

```

**Comment by Holmes7** [comment]
I have added the requested changes

**Comment by yashrsharma44** [comment]
LGTM!

**Comment by yashrsharma44** [comment]
@Holmes Thanks for the PR! 💪

**Pull request merged**
