### PR TITLE
Work on Issue #20 along with other changes

### PR DESCRIPTION
**Pull request by Holmes7**
Build and Lint targets added to Makefile.
Ran gofmt -s -w and main.go utils/loginrequired.go and utils/logs/pkg/logs.go were changed.
Added .DS_Store to .gitignore

### CODE REVIEW

**Comment by Holmes7** [comment]
This doesn't solve the issue completely but I have tried to do as much as I could figure out. 
The additional changes aren't mentioned for this issue but I thought I should review them as well. If not needed I will make the needful changes to the commit.

Doubts 
I am not able to understand the last two tasks. If you could elaborate it would be helpful

**Comment by rakaar** [comment]
Great job @Holmes7 
Regarding the last 2 tasks - 
1. We currently don't have any tests. So you can ignore it.
2. Regarding deployment, I am not sure regarding it. But I think @yashrsharma44 was talking about a development server like frontend has one on netlify. 
@yashrsharma44  can you please once clarify

Also Please update your PR, by rebasing the master branch, and run the checks again on the updated code and commit and push it

**Comment by yashrsharma44** [comment]
For frontend, a netlify deployment makes sense. However, for backend, apart from tests and lint checks, it does not make sense for having a netlify deployment

**Comment by yashrsharma44** [comment]
@Holmes7 pro tip- if you add something like this -
```
Fixes #20
```
This automatically tags the issue, and once this pr is merged, that issue would be closed automatically 😎

**Pull request closed without merging**
