### PR TITLE
Project Endpoints for getting started

### PR DESCRIPTION
**Pull request by rakaar**
I added Project endpoints to get started.( bcoz Mentor involves complication like OAuth). Made this PR to get started with making decisions about important points like "what directory structure", "what response formats", "error handling"

Things that are wrong 
- Used SQLite, since only for testing 

Things need to be changed/opinion required
- directory structure
- DB obviously
- Error handling(Need to be added in places where comments are there. At other places too. Let's decide one standard Method to do so) 
- Response formats (let's decide and keep the simplest possible)

### CODE REVIEW

**Comment by rakaar** [comment]
CTMs u also review. And please provide your feedback

**Comment by dibyadas** [comment]
Hey @rakaar, thanks for getting this started! I would suggest the CTMs to keep following this from the nascent stage or it will be difficult to understand later on. Also, set goals. Define particular things to be done by the end of the week(for example) in a task planner and stick to it. 
@Ayushk4 Could you keep a tab on this?

**Comment by rakaar** [comment]
@dibyadas 
There is a goal which we currently have
 To complete mentor registration by 10th of July.  If this goes good, we continue in golang.

**Comment by Ayushk4** [comment]
@dibyadas I have not worked with Go for over a year and didn't use much, to begin with; So, I won't be able to do the reviews on this.

**Comment by dibyadas** [comment]
> To complete mentor registration by 10th of July. If this goes good, we continue in golang.

This is good although I meant micro deadlines. Like complete projects routes in next 2 days. Something along those lines. Infact feel free to follow whatever method that's comfortable to complete the tasks.

**Comment by rakaar** [comment]
Added Error handling as per [this](https://golang.org/doc/articles/wiki/#tmp_9)
and by slightly modifying [this](https://gorm.io/docs/error_handling.html) 
did so to maintain uniformity

so this is the standard style
```
err := Operation
if err != nil {
http.Error(w, err.Error(), http.Status)
return
}
```

**Pull request merged**
